export const BRANDS_DATA = [
  {
    id: "brand-01",
    region: "서울",
    area: "서초",
    image: "/reference/ref1/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref1/1.webp",
      "/reference/ref1/2.webp",
      "/reference/ref1/3.webp",
      "/reference/ref1/4.webp",
    ],
  },
  {
    id: "brand-02",
    region: "부산",
    area: "영도",
    image: "/reference/ref2/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref1/1.webp",
      "/reference/ref1/2.webp",
      "/reference/ref1/3.webp",
      "/reference/ref1/4.webp",
    ],
  },
  {
    id: "brand-03",
    region: "강원",
    area: "삼척",
    image: "/reference/ref3/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref3/1.webp",
      "/reference/ref3/2.webp",
      "/reference/ref3/3.webp",
      "/reference/ref3/4.webp",
    ],
  },
  {
    id: "brand-04",
    region: "전북",
    area: "전주",
    image: "/reference/ref4/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref4/1.webp",
      "/reference/ref4/2.webp",
      "/reference/ref4/3.webp",
      "/reference/ref4/4.webp",
    ],
  },
  {
    id: "brand-05",
    region: "경기",
    area: "가평",
    image: "/reference/ref5/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref5/1.webp",
      "/reference/ref5/2.webp",
      "/reference/ref5/3.webp",
      "/reference/ref5/4.webp",
    ],
  },
  {
    id: "brand-06",
    region: "경남",
    area: "양산",
    image: "/reference/ref6/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref6/1.webp",
      "/reference/ref6/2.webp",
      "/reference/ref6/3.webp",
      "/reference/ref6/4.webp",
    ],
  },
  {
    id: "brand-07",
    region: "고양",
    area: "벽제",
    image: "/reference/ref7/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref7/1.webp",
      "/reference/ref7/2.webp",
      "/reference/ref7/3.webp",
      "/reference/ref7/4.webp",
    ],
  },
  {
    id: "brand-08",
    region: "고양",
    area: "화정",
    image: "/reference/ref8/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref8/1.webp",
      "/reference/ref8/2.webp",
      "/reference/ref8/3.webp",
      "/reference/ref8/4.webp",
    ],
  },
  {
    id: "brand-09",
    region: "충남",
    area: "서산",
    image: "/reference/ref9/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref9/1.webp",
      "/reference/ref9/2.webp",
      "/reference/ref9/3.webp",
      "/reference/ref9/4.webp",
    ],
  },
  {
    id: "brand-10",
    region: "파주",
    area: "금촌",
    image: "/reference/ref10/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref10/1.webp",
      "/reference/ref10/2.webp",
      "/reference/ref10/3.webp",
      "/reference/ref10/4.webp",
    ],
  },
  {
    id: "brand-11",
    region: "파주",
    area: "탄현",
    image: "/reference/ref11/1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/ref11/1.webp",
      "/reference/ref11/2.webp",
      "/reference/ref11/3.webp",
      "/reference/ref11/4.webp",
    ],
  },
];
