export const BRANDS_DATA = [
  {
    id: "brand-01",
    region: "서울",
    area: "서초",
    image: "/reference/ref1/1.webp",
    description1: "강남 중심의 프리미엄 레지던스형 스테이.",
    description2: "비즈니스와 장기투숙에 최적화된 공간입니다.",
    photos: [
      "/reference/ref1/1.webp",
      "/reference/ref1/2.webp",
      "/reference/ref1/3.webp",
      "/reference/ref1/4.webp",
    ],
  },
  {
    id: "brand-02",
    region: "부산",
    area: "영도",
    image: "/reference/ref2/1.webp",
    description1: "영도 바다를 품은 오션뷰 감성 호텔.",
    description2: "관광과 휴식을 함께 누리는 입지입니다.",
    photos: [
      "/reference/ref2/1.webp",
      "/reference/ref2/2.webp",
      "/reference/ref2/3.webp",
      "/reference/ref2/4.webp",
    ],
  },
  {
    id: "brand-03",
    region: "강원",
    area: "삼척",
    image: "/reference/ref3/1.webp",
    description1: "해변 인접 루프탑 수영장 호텔.",
    description2: "관광 수요를 흡수하는 리조트형 숙소입니다.",
    photos: [
      "/reference/ref3/1.webp",
      "/reference/ref3/2.webp",
      "/reference/ref3/3.webp",
      "/reference/ref3/4.webp",
    ],
  },
  {
    id: "brand-04",
    region: "전북",
    area: "전주",
    image: "/reference/ref4/1.webp",
    description1: "루프탑과 감성을 갖춘 도심 호텔.",
    description2: "애견동반 수요까지 아우르는 공간입니다.",
    photos: [
      "/reference/ref4/1.webp",
      "/reference/ref4/2.webp",
      "/reference/ref4/3.webp",
      "/reference/ref4/4.webp",
    ],
  },
  {
    id: "brand-05",
    region: "경기",
    area: "가평",
    image: "/reference/ref5/1.webp",
    description1: "자연 속 힐링 리조트형 호텔.",
    description2: "가족·커플 수요가 꾸준한 관광 입지입니다.",
    photos: [
      "/reference/ref5/1.webp",
      "/reference/ref5/2.webp",
      "/reference/ref5/3.webp",
      "/reference/ref5/4.webp",
    ],
  },
  {
    id: "brand-06",
    region: "경남",
    area: "양산",
    image: "/reference/ref6/1.webp",
    description1: "프라이빗 풀빌라 중심 스테이.",
    description2: "휴식형 고객에 특화된 독립 공간입니다.",
    photos: [
      "/reference/ref6/1.webp",
      "/reference/ref6/2.webp",
      "/reference/ref6/3.webp",
      "/reference/ref6/4.webp",
    ],
  },
  {
    id: "brand-07",
    region: "고양",
    area: "벽제",
    image: "/reference/ref7/1.webp",
    description1: "합리적 가격의 실속형 숙소.",
    description2: "안정적 고정 수요 기반 운영입니다.",
    photos: [
      "/reference/ref7/1.webp",
      "/reference/ref7/2.webp",
      "/reference/ref7/3.webp",
      "/reference/ref7/4.webp",
    ],
  },
  {
    id: "brand-08",
    region: "고양",
    area: "화정",
    image: "/reference/ref8/1.webp",
    description1: "역세권 접근성의 도심 모텔.",
    description2: "가성비 중심의 회전율형 구조입니다.",
    photos: [
      "/reference/ref8/1.webp",
      "/reference/ref8/2.webp",
      "/reference/ref8/3.webp",
      "/reference/ref8/4.webp",
    ],
  },
  {
    id: "brand-09",
    region: "충남",
    area: "서산",
    image: "/reference/ref9/1.webp",
    description1: "산업단지 인접 비즈니스 호텔.",
    description2: "출장 수요 기반의 안정 운영 모델입니다.",
    photos: [
      "/reference/ref9/1.webp",
      "/reference/ref9/2.webp",
      "/reference/ref9/3.webp",
      "/reference/ref9/4.webp",
    ],
  },
  {
    id: "brand-10",
    region: "파주",
    area: "금촌",
    image: "/reference/ref10/1.webp",
    description1: "금촌 상권 중심 입지 호텔.",
    description2: "지역 내 인지도 높은 운영 자산입니다.",
    photos: [
      "/reference/ref10/1.webp",
      "/reference/ref10/2.webp",
      "/reference/ref10/3.webp",
      "/reference/ref10/4.webp",
    ],
  },
  {
    id: "brand-11",
    region: "파주",
    area: "탄현",
    image: "/reference/ref11/1.webp",
    description1: "관광지 인접 가족형 숙소.",
    description2: "주말 관광 수요에 강한 구조입니다.",
    photos: [
      "/reference/ref11/1.webp",
      "/reference/ref11/2.webp",
      "/reference/ref11/3.webp",
      "/reference/ref11/4.webp",
    ],
  },
];
