export const BRANDS_DATA = [
  {
    id: "brand-01",
    region: "인천광역시",
    area: "중구",
    image: "/reference/image-1.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/building1/img-1.webp",
      "/reference/building1/img-2.webp",
      "/reference/building1/img-3.webp",
      "/reference/building1/img-4.webp",
    ],
  },
  {
    id: "brand-02",
    region: "전라북도",
    area: "전주",
    image: "/reference/image-2.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/building2/img-1.webp",
      "/reference/building2/img-2.webp",
      "/reference/building2/img-3.webp",
      "/reference/building2/img-4.webp",
    ],
  },
  {
    id: "brand-03",
    region: "경기도",
    area: "가평 1",
    image: "/reference/image-3.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/building3/img-1.webp",
      "/reference/building3/img-2.webp",
      "/reference/building3/img-3.webp",
      "/reference/building3/img-4.webp",
    ],
  },
  {
    id: "brand-04",
    region: "경기도",
    area: "가평 2",
    image: "/reference/image-4.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/building4/img-1.webp",
      "/reference/building4/img-2.webp",
      "/reference/building4/img-3.webp",
      "/reference/building4/img-4.webp",
    ],
  },
  {
    id: "brand-05",
    region: "경기도",
    area: "파주",
    image: "/reference/image-5.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/building5/img-1.webp",
      "/reference/building5/img-2.webp",
      "/reference/building5/img-3.webp",
      "/reference/building5/img-4.webp",
    ],
  },
  {
    id: "brand-06",
    region: "경기도",
    area: "일산",
    image: "/reference/image-6.webp",
    description1: "게임과 힐링이 만나는 특별한 공간",
    description2: "일상에서 벗어난 나만의 시간을 경험하세요",
    photos: [
      "/reference/building6/img-1.webp",
      "/reference/building6/img-2.webp",
      "/reference/building6/img-3.webp",
      "/reference/building6/img-4.webp",
    ],
  },
];
